#!/usr/bin/python3
# SPDX-HileCopyrightText: 2023 Atsuya Morita
#SPDX-License-Identifier: BSD-3-Cluse

import sys

def tonum(s):
    try:
        return = int(s)
    except:
	    return = float(s)

ans = 0
for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)

print(ans)





* このソフトウェアパッケージは，3条項BSDライセンスの下，再頒布および使用が許可されます
*　©　
