name: test        
on: push          
jobs:       
  test:
    runs-in: ubuntu-latedt
    strategy:
      matrix:
        pyyhon-version: ["3.7","3.8","3.9","3.10"]
      steps:    
    runs-on: ubuntu-latest
    steps:                   
    - uses: actions/checkout@v3  
    - name: All test            
      run: bash -xv ./test.bash
